### PR TITLE
Fix useMMKVStorage typing and falsy values persistance

### LINKED ISSUE #253: [Question] useMMKVStorage typing not mimicking useState
Hello! Firstly I wanna thanks @ammarahm-ed for this awesome library and work since I think this is my first time posting here, you're a life-saver. By the way, I don't know how to reference files so I'll post codeblocks along with paths.

From my understanding, the `useMMKVStorage` hook is made to mimic the behaviour of useState but with persistent storage, if that's the case then there is some weird typing behaviour which it's an easy fix, but the reason I'm not opening a PR is because of the first part of this sentence: it's my understanding, so I don't really know if this is working as intended or not:

On `/src/hooks/useMMKV.ts` line 60, the typing for `useMMKVStorage` is the following:
```typescript
const useMMKVStorage = <T>(
  key: string,
  storage: MMKVInstance,
  defaultValue?: T | null | undefined // <-- Here
): [
  value: T | null | undefined, // <-- And here
  setValue: (value: T | ((prevValue: T | null | undefined /* <-- Aand here */) => T)) => void
] => {...}
```

See, with the type definitions of react, `useState` uses function overloading to type accordingly if you have passed or not the defaultValue:
```typescript
const [value, setValue] = useState<string>() // Type of value: string | undefined
const [value, setValue] = useState('default') // Type of value: string
```
because if you have a default value, the value returned must not be null or undefined, that's where `useMMKVStorage` differs:
```typescript
const [value, setValue] = useMMKVStorage<string>('key', storage) // Type of value: string | null | undefined, currently fine
const [value, setValue] = useMMKVStorage<string>('key', storage, 'default') // Type of value: string | null | undefined, how can value ever be null or undefined if it has a default value?
```

And also is it intentional to change the default value from undefined to null on `/src/hooks/useMMKV.ts` line 157? 
 ```
   defaultValue = defaultValue === undefined ? null : defaultValue;
   return [valueType === 'boolean' ? value : value || defaultValue, setNewValue];
 ```
 
Well those are all my questions/points, thanks for reading :)

### PR DESCRIPTION
**Pull request by douugdev**
Fixes #253 and possibly an issue related with #248

This PR rewrites some typing for the `useMMKVStorage` such as it let the returned type of `value` to be null or undefined only when no `defaultValue` is set.

It removes the logical OR operator for returning a `defaultValue` since it causes unintended behaviour when there was a `defaultValue` set but the value itself is falsy, like an empty string or the number 0.  
```typescript
  - return [valueType === 'boolean' ? value : value || defaultValue, setNewValue];
  + return [value ?? (defaultValue === undefined ? null : defaultValue), setNewValue];
```

### CODE REVIEW

File: src/hooks/useMMKV.ts [hunk 1]
```diff
@@ -24,14 +24,34 @@ import { getDataType, getInitialValue } from './functions';
...
+  (storage: MMKVInstance) =>
+  <T = undefined>(key: string, defaultValue?: T) => {
     if (!key || typeof key !== 'string' || !storage)
       throw new Error('Key and Storage are required parameters.');
-    return useMMKVStorage<T>(key, storage, defaultValue);
+    if (defaultValue === undefined) {
+      return useMMKVStorage<T>(key, storage);
+    } else {
+      return useMMKVStorage<T>(key, storage, defaultValue);
+    }
```
Comment (ammarahm-ed) [inline src/hooks/useMMKV.ts]: This seems to be redundant. Because if we do not pass the `defaultValue` parameter, it will become undefined anyways.

File: src/hooks/useMMKV.ts [hunk 2]
```diff
@@ -154,8 +171,10 @@ export const useMMKVStorage = <T>(
     [key, storage, valueType]
   );
 
-  defaultValue = defaultValue === undefined ? null : defaultValue;
-  return [valueType === 'boolean' ? value : value || defaultValue, setNewValue];
+  return [
+    valueType === 'boolean' ? value : value || (defaultValue === undefined ? null : defaultValue),
+    setNewValue
+  ];
```
Comment (ammarahm-ed) [inline src/hooks/useMMKV.ts]: After mimicking the behavior of `useState` we should remove `defaultValue === undefined` check and not decide if the value should be null or undefined unless the default value is explicitly set to `null`.

Something like this.
```js
return [
    valueType === 'boolean' || valueType === 'number' ? value : value || defaultValue,
    setNewValue
  ];
```
Numbers and booleans can have falsy values that are still required.

**Review by ammarahm-ed — CHANGES_REQUESTED** [review]

**Comment by douugdev** [comment]
Sorry for the delay! Rough weekend haha. Working on the changes at the moment.

File: src/hooks/useMMKV.ts (hunk 2 above)
Comment (douugdev) [reply src/hooks/useMMKV.ts]: I'll remove the `defaultValue === undefined`, but regarding the falsy values, I solved it on the following commit [eddf740](https://github.com/ammarahm-ed/react-native-mmkv-storage/pull/254/commits/eddf740083ccbbd66296388b924fd876355bf529#diff-ec5f071387ad12855e15fb68c97bdbdbb3a6b8993d604293dc87be8f51d5bda9R176) using the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator), was that not valid? Because checking the value type still returns the default value if you pass in an empty string `""`

Comment (ammarahm-ed) [reply src/hooks/useMMKV.ts]: @douugbr I think we should not decide for cases other than numbers (0, -1) & boolean (false) values. It's responsibility of the app/dev to pass a valid value, so if it's an empty string, it's an empty string. Also i think overriding the `defaultValue` passed will cause more inconsistencies and confusion so we should do it only when necessary.

**Comment by ammarahm-ed** [comment]
Looks good! Thank you.
